### ISSUE TITLE
ARBHOME not set (w/o wrapper script)

### ISSUE THREAD

**Issue by epruesse** [epruesse/SINA#15]
When not using the wrapper script, e.g. installation via Bioconda, the `ARBHOME` environment variable may not be set causing `arb_pt_server` to fail.

Encode the path in the binary and try to find ARB at startup.

**Comment by epruesse** [comment]
fixed by 62239e37e5cf439598137e5f7b8344a6c3ab3759 ff

**Comment by mdehollander** [comment]
Still getting the same error with `1.3.4` installed from bioconda:

```
mattias@mattias-notebook:~$  conda activate sina-1.3.4
(sina-1.3.4) mattias@mattias-notebook:~$ printenv | grep ARB
ARBHOME=
ARBHOME_BACKUP=
(sina-1.3.4) mattias@mattias-notebook:~$ arb_pt_server
Fatal ERROR: Environment Variable ARBHOME not found !!!
   Please set 'ARBHOME' to the installation path of ARB
sum of above:  0 b
overall alloc: 0 b
(sina-1.3.4) mattias@mattias-notebook:~$ conda list | grep sina
# packages in environment at /home/mattias/miniconda3/envs/sina-1.3.4:
sina                      1.3.4                h4ef8376_2    bioconda
```

**Comment by epruesse** [comment]
@mdehollander Darn. Looking into it. Does the tarball from the releases work for you at least?

**Comment by epruesse** [comment]
Err. Wait. That's not an issue with SINA, but with the `arb-bio` package. In theory, there should be an activate script that sets ARBHOME when you activate the environment.

**Comment by epruesse** [comment]
Oh. Wait. Sigh. Need to update the `arb-bio` package yet again.

The activate script is part of `arb-bio`, but SINA installs only `arb-bio-tools` and `libarbdb`, so no activate script and hence no ARBHOME.

It is something of a corner case. SINA itself will set ARBHOME doing some hacky guesswork (using the memory address of ARB library calls to get the on-disk location of libARBDB and deducing ARBHOME from that). I don't think I want to add that kind of stuff to ARB itself.

**Comment by epruesse** [comment]
Updated the ARB package https://github.com/bioconda/bioconda-recipes/pull/10889

**Comment by mdehollander** [comment]
Perfect, I can confirm it works now. Thanks.
